// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  frontend: [
    {
      type: 'autogenerated',
      dirName: 'frontend',
    },
  ],
  CS: [
    {
      type: 'autogenerated',
      dirName: 'CS',
    },
  ],
};

module.exports = sidebars;
